GATE_BUFFER_MIN = 15
CREW_REST_MIN = 20
CREW_TRANSIT_MIN = 30
MIN_CONNECTION_MIN = 30
MAX_CASCADE_DEPTH = 3

DAY_START = "06:00"
DAY_END = "22:00"

DECISION_TYPES = [
    "DELAY_APPLIED",
    "GATE_REASSIGNED",
    "CREW_REASSIGNED",
    "BAGGAGE_REROUTED",
    "BAGGAGE_AT_RISK",
    "BAGGAGE_REBOOKED",
    "CASCADE_BUMP",
    "NO_ACTION_NEEDED",
    "BLOCKED",
    "SCENARIO_RESET",
    "CHAOS_TRIGGERED",
    "FLIGHT_CANCELLED",
]
